add_newline = true

format = """\
[󱞬 ](g_fg)[](g_red)$os$username$sudo\
[▓▒░](fg:g_red bg:g_orange)$directory\
[▓▒░](fg:g_orange bg:g_yellow)$nix_shell$cmd_duration$status\
[ ](g_yellow)[  ](g_fg)$fill[   ](g_fg)\
[ ](g_green)$git_branch$git_status\
[▓▒░](fg:g_green bg:g_aqua)$c$deno$golang$java$lua$nim$nodejs$ruby$rust$php$python\
[▓▒░](fg:g_aqua bg:g_blue)$package\
[▓▒░](fg:g_blue bg:g_purple)$time\
[](g_purple)
[󱞪 ](g_fg)$character\
"""

palette = "gruvbox_gradient"

[palettes.gruvbox_gradient]
g_red = "#fb4934"
g_orange = "#fe8019"
g_yellow = "#fabd2f"
g_green = "#b8bb26"
g_aqua = "#8ec07c"
g_blue = "#83a598"
g_purple = "#d3869b"
g_bg = "#282828"
g_fg = "#ebdbb2"

[os]
style = "fg:g_bg bg:g_red"
disabled = false
symbols = { Arch = " ", NixOS = "󱄅 " }

[username]
disabled = false
show_always = true
style_user = "fg:g_bg bg:g_red"
style_root = "fg:g_bg bg:g_red"
format = "[$user]($style)"

[sudo]
disabled = false
symbol = " "
style = "fg:g_bg bg:g_red"
format = "[$symbol]($style)"

[directory]
style = "fg:g_bg bg:g_orange bold"
format = "[$path]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = " "

[nix_shell]
format = "[ 󱄅 $name]($style)"
style = "fg:g_bg bg:g_yellow bold"

[cmd_duration]
format = "[  $duration]($style)"
style = "fg:g_bg bg:g_yellow bold"

[status]
disabled = false
symbol = "[  ](fg:g_red bg:g_yellow)"
success_symbol = "[ 󰗡 ](fg:g_green bg:g_yellow)"
success_style = "fg:g_green bg:g_yellow"
failure_style = "fg:g_red bg:g_yellow"
format = "$symbol([$status]($style))"

[git_branch]
symbol = ""
style = "fg:g_bg bg:g_green italic"
format = "[$symbol $branch]($style)"

[git_status]
style = "fg:g_bg bg:g_green italic"
format = "[$all_status$ahead_behind]($style)"

[c]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[deno]
symbol = "🦖"
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[golang]
symbol = " "
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[java]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[php]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[python]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[lua]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[nim]
symbol = "󰆥"
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[nodejs]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[ruby]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[rust]
symbol = ""
style = "fg:g_bg bg:g_aqua"
format = "[$symbol $version]($style)"

[package]
symbol = "󰏗 "
format = "[$symbol$version]($style)"
style = "fg:g_bg bg:g_blue"

[fill]
symbol = "  "
style = "g_fg"

[time]
disabled = false
time_format = "%I:%M%p"
style = "fg:g_bg bg:g_purple bold"
format = "[ $time]($style)"

[character]
success_symbol = "[](g_aqua) [I](bold fg:g_bg bg:g_green)"
error_symbol = "[](g_aqua) [I](bold fg:g_bg bg:g_green)"
vimcmd_symbol = "[](g_aqua) [N](bold fg:g_bg bg:g_blue)"
vimcmd_visual_symbol = "[](g_aqua) [V](bold fg:g_bg bg:g_purple)"
vimcmd_replace_one_symbol = "[](g_aqua) [R](bold fg:g_bg bg:g_red)"
